spring.datasource.url=jdbc:postgresql://ep-red-shape-a13atbqo-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=MẬT_KHẨU_NEON_CỦA_MÀY
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
